/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User,
    wallets: Wallet,
    transactions: Transactions
    // 'payload-preferences': PayloadPreference
  }
  globals: {}
}
export interface User {
  id: string
  firstName?: string
  lastName?: string
  roles?: ('admin' | 'user')[]
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string
  resetPasswordExpiration?: string
  salt?: string
  hash?: string
  loginAttempts?: number
  lockUntil?: string
  password?: string
}
export interface Wallet{
  userId: User,
  name: string,
  availableBalance: number,
  updatedAt: string
  createdAt: string
}
export interface Transactions{
  type: string,
  reason: string,
  amount: number,
  userId: User,
  createdAt: Date
}
export interface Contributions{
  id: string,
  users: User[],
  amountToContribute: number,
  totalAmount: number,
  totalUsers: number,
  paidUsers: User[],
  createdAt: Date,
  status: string,
  frequency: string,
  paybackDate: Date,
  reachedUser: User
}



declare module 'payload' {
  export interface GeneratedTypes {
    collections: {
      users: User,
      wallets: Wallet,
      transactions: Transactions,
      contributions: Contributions
    }
  }
}
