/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User,
    wallets: Wallet,
    transactions: Transactions
    // 'payload-preferences': PayloadPreference
  }
  globals: {}
}
export interface User {
  id: string
  firstName?: string
  lastName?: string
  roles?: ('admin' | 'user')[]
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string
  resetPasswordExpiration?: string
  salt?: string
  hash?: string
  loginAttempts?: number
  lockUntil?: string
  password?: string
}
export interface Wallet{
  id: string,
  userId: string,
  name: string,
  availableBalance: number,
  updatedAt: string
  createdAt: string
}
export interface Transactions{
  id: string,
  type: string,
  reason: string,
  amount: number,
  userId: string,
  createdAt: Date
}
export interface performBankOp{
  id: string,
  wallet: string,
  type: string,
  reason: string,
  amount: number
}
export interface Contributions{
  id: string,
  members: string[],
  amountToContribute: number,
  totalSaving: number,
  payoutHistory: string[],
  payDate: Date,
  status: string,
  intervals: string,
  rotationOrder: string
}



declare module 'payload' {
  export interface GeneratedTypes {
    collections: {
      users: User,
      wallets: Wallet,
      transactions: Transactions,
      contributions: Contributions,
      perform_bank_op:performBankOp
    }
  }
}
